#undef _BITS_TYPESIZES_H
#undef __STRICT_ANSI__
#undef __u_char_defined
#undef __ino_t_defined
#undef __dev_t_defined
#undef __nlink_t_defined
#undef __off_t_defined
#undef __id_t_defined
#undef __ssize_t_defined
#undef __daddr_t_defined
#undef __clock_t_defined
#undef __time_t_defined
#undef __clockid_t_defined
#undef __timer_t_defined
#undef __timespec_defined
#undef _STRUCT_TIMEVAL
#undef __suseconds_t_defined
#undef __blksize_t_defined
#undef __blkcnt_t_defined
#undef ____mbstate_t_defined
#undef __mbstate_t_defined
#undef _WINT_T
#undef __FILE_defined
#undef _ANSI_STDARG_H_
#undef __GNUC_VA_LIST
#undef ____FILE_defined
#undef __USE_EXTERN_INLINES
#undef _FORTIFY_SOURCE
#undef __OPTIMIZE__
#undef _BITS_STAT_H
#undef F_LOCK
#undef __uClinux__
#undef ____gwchar_t_defined
#undef __cpu_set_t_defined
#undef _ASM
#undef __need_sig_atomic_t
#undef __need_sigset_t
#undef __have_siginfo_t
#undef __have_sigval_t
#undef __have_pthread_attr_t
#undef __have_sigevent_t
#undef __sigset_t_defined
#undef _VA_LIST_DEFINED
#undef _VA_LIST_
#undef _VA_LIST
#undef _VA_LIST_T_H
#undef __va_list__
#undef __BSD_NET2__
#undef _STDDEF_H_
#undef _ANSI_STDDEF_H
#undef __STDDEF_H__
#undef _GCC_MAX_ALIGN_T
#undef _IO_MTSAFE_IO
#undef _IO_USE_OLD_IO_FILE
#undef __int8_t_defined
#undef _STDLIB_H
#undef __need_malloc_and_calloc
#undef __COMPAR_FN_T
#undef __ldiv_t_defined
#undef __lldiv_t_defined
#undef _UTSNAME_SYSNAME_LENGTH
#undef _UTSNAME_NODENAME_LENGTH
#undef _UTSNAME_RELEASE_LENGTH
#undef _UTSNAME_VERSION_LENGTH
#undef _UTSNAME_MACHINE_LENGTH
#undef _SYS_WAIT_H
#undef __ENUM_IDTYPE_T
#undef SYSLOG_NAMES
#undef __useconds_t_defined
#undef __intptr_t_defined
#undef _BITS_UIO_H
#undef __socklen_t_defined
#undef _EXTERN_INLINE
#undef _ISwbit
#undef __ASSEMBLY__
#undef __kernel_long_t
#undef __kernel_ino_t
#undef __kernel_suseconds_t
#undef __kernel_size_t
#undef __kernel_fsid_t
#undef _DIR_dirfd
#undef _UAPI_LINUX_IN6_H
#undef _UAPI_IPV6_H
#undef __USE_KERNEL_IPV6_DEFS
#undef TTYDEFCHARS
#undef __FAST_MATH__
#undef __CORRECT_ISO_CPP_STRING_H_PROTO
#undef _OPENMP
#undef __CORRECT_ISO_CPP_STRINGS_H_PROTO
